name: Auto Sync Codespace

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Install GitHub CLI
        run: sudo apt-get install gh -y

      - name: Authenticate GitHub CLI
        env:
          MY_CODESPACE_PAT: ${{ secrets.CODESPACE_PAT }}
        run: echo "${MY_CODESPACE_PAT}" | gh auth login --with-token

      - name: Get Codespace Name
        run: |
          echo "Listing available Codespaces..."
          gh codespace list --json name,state,repository
          CS_NAME=$(gh codespace list --json name --jq '.[0].name')
          echo "Codespace name: $CS_NAME"
          echo "codespace_name=$CS_NAME" >> $GITHUB_ENV

      - name: Pull latest changes in Codespace
        run: |
          echo "Attempting to pull latest changes in Codespace..."
          gh codespace ssh --codespace ${{ env.codespace_name }} -- 'cd /workspaces/Koppsnipern && git pull origin main'
