name: Auto Sync Codespace

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Set up GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
          type -p curl >/dev/null || sudo apt-get install curl -y
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt-get update
          sudo apt-get install gh -y

      - name: Authenticate with PAT
        run: echo "${{ secrets.CODESPACE_PAT }}" | gh auth login --with-token

      - name: Git Pull in specific Codespace
        run: |
          CODESPACE_NAME="jubilant-space-engine"
          echo "Syncing codespace: $CODESPACE_NAME"
          gh codespace ssh -c "$CODESPACE_NAME" -- '
            REPO_DIR=$(find /workspaces -name ".git" -type d -exec dirname {} \; | head -n 1)
            if [ -n "$REPO_DIR" ]; then
              echo "✅ Found repository at: $REPO_DIR"
              echo "📡 Running git pull..."
              git -C "$REPO_DIR" pull --verbose
            else
              echo "❌ No git repository found in /workspaces."
              exit 1
            fi
          '
