name: Auto Sync Codespace

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Set up GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
          type -p curl >/dev/null || sudo apt-get install curl -y
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt-get update
          sudo apt-get install gh -y

      - name: Authenticate with PAT
        run: echo "${{ secrets.CODESPACE_PAT }}" | gh auth login --with-token

      - name: Find active Codespace
        id: findspace
        run: |
          CS_NAME=$(gh codespace list --json name,state --jq '.[] | select(.state=="Available") | .name' | head -n 1)
          echo "codespace_name=$CS_NAME" >> $GITHUB_OUTPUT

      - name: Git Pull in Codespace
        if: steps.findspace.outputs.codespace_name != ''
        run: |
          echo "Syncing codespace: ${{ steps.findspace.outputs.codespace_name }}"
          gh codespace ssh -c "${{ steps.findspace.outputs.codespace_name }}" -- 'cd /workspaces/Koppsnipern && git pull'
