name: Update TREE
on:
  push:
    paths:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install -y tree
      - run: tree -I 'node_modules|.venv|dist' -L 3 > TREE.md
      - run: |
          git config --global user.name "CI Bot"
          git config --global user.email "ci@example.com"
          git add TREE.md
          git commit -m "ci: auto-update TREE" || echo "No changes"
          git push
