name: Update repository tree
on:
  push:
    paths:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: { contents: write }
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install -y tree
      - run: |
          tree -I 'node_modules|.venv|dist' -L 3 > TREE.md
          if git diff --quiet TREE.md; then
            echo "TREE.md unchanged"
          else
            git config --global user.email "actions@github.com"
            git config --global user.name  "GitHub Actions"
            git add TREE.md
            git commit -m "ci: auto-update TREE.md"
            git push
          fi
